USE INDIANMUSIC
GO

-- ====================================
-- Languages
-- ====================================
INSERT INTO Languages ([Name], [Description]) VALUES
(N'English',N'Offical language spoken almost all over the world'),
(N'Hindi',N'Official language, widely spoken, evolved from Sanskrit.'),
(N'Bengali',N'Rich literary tradition, second most spoken language in India.'),
(N'Marathi',N'Spoken in Maharashtra, rich literature and media presence.'),
(N'Gujarati',N'Spoken in Gujarat, strong commercial and literary presence.'),
(N'Punjabi',N'Spoken in Punjab, rich folk and religious literature.'),
(N'Odia',N'Spoken in Odisha, classical literary heritage.'),
(N'Assamese',N'Spoken in Assam, important literary language.'),
(N'Rajasthani',N'Spoken in Rajasthan, includes dialects like Marwari.'),
(N'Kashmiri',N'Spoken in Jammu & Kashmir, rich cultural history.'),
(N'Tamil',N'One of the oldest living classical languages.'),
(N'Telugu',N'Rich literary tradition, Dravidian language.'),
(N'Kannada',N'Known for classical and modern literature.'),
(N'Malayalam',N'Rich literary and cinematic tradition.'),
(N'Tulu',N'Spoken in coastal Karnataka, Dravidian language.'),
(N'Santali',N'Tribal language, recognized in the Eighth Schedule.'),
(N'Mundari',N'Tribal language spoken in central India.'),
(N'Khasi',N'Spoken in Meghalaya, tribal language.'),
(N'Bodo',N'Spoken by Bodo tribe, part of Sino-Tibetan family.'),
(N'Mizo',N'Spoken in Mizoram, tribal language.'),
(N'Ao Naga',N'Spoken by Ao Naga tribe in Nagaland.'),
(N'Ladakhi',N'Spoken in Ladakh and Himalayan region.'),
(N'Nefamese',N'Lingua franca in Arunachal Pradesh.'),
(N'Great Andamanese',N'Indigenous language of the Andaman Islands.');

--select * from Languages
--select * from Categories
--truncate table Categories
-- ====================================
-- Categories
-- ====================================

INSERT INTO Categories ([Name], [Description], ParentID) VALUES 
('Artist Type','',NULL),
('Music Director','',1),
('Classical Composer','',1),
('Lyricist','',1),
('Vocalist / Singer','',1),
('Instrumentalist','',1),
('Instrument Type','',NULL),
('Wind Instrument','',7),
('Bansuri','Bamboo Flute, Hindustani Classical',8),
('Venu','South Indian Bamboo Flute (Carnatic)',8),
('Shehnai','Double-Reed Instrument, Auspicious Occasions',8),
('Nadaswaram','Long Double-Reed, Loud, South Indian Temple Music',8),
('Pungi / Been','Snake Charmer’S Reed Instrument',8),
('Algoza','Double Flute From Punjab & Rajasthan',8),
('Sundari','Short Reed Instrument, Maharashtra Folk',8),
('Shankh (Conch shell)','Blown In Rituals And Devotional Music',8),
('Mashak / Titti','Bagpipe-Like Folk Instrument From North India',8),
('Nagphani','Serpent-Shaped Brass Wind Instrument, Folk',8),
('String Instrument','',7),
('Sitar','Long-Necked Plucked Lute, Hindustani Classical',19),
('Guitar','Guitar is widely accepted in modern Indian classical fusion and film music.',19),
('Sarod','Fretless Lute With A Deep, Resonant Tone',19),
('Veena','Ancient Lutes Used In Carnatic & Hindustani Traditions',19),
('Tanpura','Drone Instrument, Provides Harmonic Base',19),
('Esraj','Bowed String, Common In Bengal',19),
('Sarangi','Bowed String, Expressive, Used In Hindustani Music',19),
('Violin','Adapted Into Carnatic & Hindustani Music',19),
('Dilruba','Bowed String, North Indian Devotional Music',19),
('Santoor','Hammered Dulcimer From Kashmir',19),
('Rabab','Plucked Lute, Used In Folk & Sikh Traditions',19),
('Ektara','One-String Folk Drone',19),
('Kamaicha','Bowed Folk Instrument From Rajasthan',19),
('Mayuri','Peacock-Shaped Bowed Instrument',19),
('Mandolin','Adapted In Carnatic',19),
('Gottuvadhyam / Chitravina','Fretless Lute In Carnatic Music',19),
('Percussion Instrument','',7),
('Tabla','Most Popular Hindustani Percussion, Two Drums',36),
('Mridangam','Main Carnatic Percussion, Double-Headed Drum',36),
('Pakhawaj','Older Barrel Drum, Predecessor Of Tabla',36),
('Dhol','Double-Sided Folk Drum (Punjab, Gujarat, Etc.)',36),
('Dholak','Smaller Dhol, Widely Used In Folk And Light Music',36),
('Khol','Assamese & Bengali Devotional Drum',36),
('Kanjira','South Indian Frame Drum With Jingles',36),
('Chenda','Loud Cylindrical Drum From Kerala',36),
('Thavil','South Indian Barrel Drum, Used With Nadaswaram',36),
('Madal / Maddale','Nepali/Folk Double-Sided Drum',36),
('Nagada / Nakkara','Kettle Drums Used In Folk/Traditional Music',36),
('Duff / Dafli','Frame Drum With Or Without Jingles',36),
('Manjira','Small Cymbals, Bhajans & Kirtans',36),
('Ghatam','Clay Pot Percussion (Carnatic)',36),
('Morsing','Jaw Harp (Folk & Carnatic)',36),
('Jal Tarang','Ceramic Bowls Filled With Water, Played With Sticks',36),
('Chimta','Tong-Like Folk Instrument With Jingles',36),
('Kartal / Khartal','Wooden Clappers With Jingles',36),
('Electronic & Modern Adaptations','',7),
('Harmonium','Harmonium Is A Reed Pump Organ, Central To Many Traditions',55),
('Electric Veena / Electric Mandolin','Modern Adaptations',55),
('Keyboard','Keyboard Is A Reed Pump Organ, Central To Many Traditions',55),
('Electronic Tanpura','Replaces Traditional Tanpura For Drone',55),
('Music Type','',NULL),
('Odissi','',60),
('Odissi','',61),
('Chhanda','',61),
('Champu','',61),
('Hindustani Classical','',60),
('Dhrupad','Oldest And Most Traditional Style. Serious, Devotional, Meditative. Uses Alaap (Slow, Elaborate) And Dhrupad Composition With Pakhawaj Accompaniment.',65),
('Khayal','Most Popular Modern Form. More Improvisational Freedom Than Dhrupad. Usually Accompanied By Tabla & Harmonium/Sarod/Sitar.',65),
('Tarana','Fast-Paced, Uses Mnemonic Syllables (Like Tanana, Yalali).Often Performed At The End Of A Concert.',65),
('Thumri','Light Classical Style, Romantic, Devotional.Based On Bhakti And Shringara Rasa.',65),
('Tappa','Originated In Punjab, Fast, With Intricate And Quick Note Patterns.',65),
('Hori','Seasonal & Folk-Influenced Forms',65),
('Semi-classical','Linked To Festivals (E.G., Holi) And Seasons.',65),
('Bhajan','Devotional Music, Not Strictly Classical But Often Uses Classical Ragas.',65),
('Kirtan','Devotional Music to chant maha mantra in a group, Not Strictly Classical But Often Uses Classical Ragas.',65),
('Film Music','',60),
('Romantic / Love','Focus on love and relationships between characters.',75),
('Sad / Emotional / Pathos ','Express sorrow, heartbreak, longing, or separation. Often used in emotional or tragic scenes.',75),
('Dance / Party','Upbeat, rhythmic songs meant for dancing or celebration',75),
('Devotional / Bhajan','Used for religious or spiritual sequences. Can include traditional or contemporary devotional music.',75),
('Patriotic','Express national pride or unity. Used in war films, biopics, or Independence Day-related scenes.',75),
('Item / Glamour','High-energy, often sensuous songs performed by a special dancer/actor.',75),
('Folk / Regional','Based on traditional Indian folk music or regional styles.',75),
('Theme / Background','Short musical pieces associated with a character or storyline.',75),
('Reprise / Remixed','Old songs remade or adapted for a new film version.',75),
('Motivational / Inspirational','',75),
('Folk Music','',60),
('Bihu  (Assam)','Energetic folk songs performed during the Bihu festival; celebrate love, fertility, and spring.',86),
('Pandavani (Chhattisgarh)','Narrative folk theatre singing the story of the Mahabharata.',86),
('Goan (Goa)','Songs like Mando and Dulpod reflect Portuguese influence and Goan culture.',86),
('Gujarati (Gujarat)','Garba and Raas connected with Navratri, Krishna devotion, and community celebrations.',86),
('Haryanvi (Haryana)','Celebratory songs performed during marriages, births, and farming.',86),
('Dogri (Jammu)','Simple tunes sung during festivals and harvest seasons.',86),
('Santal (Jharkhand, Odisha, Bengal)','Tribal music with drums (madal) and flutes.',86),
('Jhumur (Jharkhand, West Bengal, Assam)','Dance songs performed by tribes during festivals.',86),
('Yakshagana  (Karnataka)','Musical theatre blending dialogue, songs, and dance.',86),
('Janapada Geethe (Karnataka)','Folk songs of farmers, love ballads, and devotional themes.',86),
('Padayani  (Kerala)','Performed in temple rituals with dance and drama.',86),
('Gond  (Madhya Pradesh, Chhattisgarh)','Tribal music with percussion and storytelling about gods and heroes.',86),
('Lavani (Maharashtra)','Fast-paced, rhythmic music often with dance, dealing with love and social themes.',86),
('Powada (Maharashtra)','Heroic ballads narrating stories of warriors and historical events.',86),
('Manipuri  (Manipur)','Includes Khullong Ishei (love songs) and Lai Haraoba songs (ritualistic).',86),
('Khasi  (Meghalaya)','Songs dedicated to nature, rituals, and community life.',86),
('Mizo  (Mizoram)','Includes Chai Hla (festival songs), Hlado (war chants), Nghilh Lui Hla (love songs).',86),
('Zeliang & Angami  (Nagaland)','Tribal songs about harvests, hunting, and ancestral spirits.',86),
('Odia  Music (Odisha)','Includes Dalkhai, Pala, and Sambalpuri songs.',86),
('Rajasthani  (Rajasthan)','Known for Manganiyar and Langa communities; uses sarangi, dholak, khartal.',86),
(' Music Type (Region/Locality)','Description',86),
('Villupattu (Tamil Nadu)','Narrative songs using bow-shaped instruments, often devotional.',86),
('Oppari (Tamil Nadu)','Lament songs sung during funerals.',86),
('Nautanki (UP, MP)','Folk operatic tradition with music, dance, and drama.',86),
('Bhojpuri  (Uttar Pradesh, Bihar)','Songs about daily life, love, and festivals; includes Kajri, Chaiti, Sohar.',86),
('Kumaoni & Garhwali  (Uttarakhand)','Includes spiritual songs (Jagar), seasonal songs (Chhopati), and ballads.',86),
('Baul  (West Bengal)','Mystical songs by wandering minstrels, blending devotion with philosophy.',86),
('Bhatiali (West Bengal, Bangladesh)','Sung by boatmen on rivers; flowing and soothing in nature.',86),
('Dalkhai(Odisha)','Sung by women in tribal areas, often accompanied by dhol, nagara, and cymbals; rhythmic and energetic.',86),
('Bhatiali(Odisha)','Folk song of boatmen. Soothing songs reflecting life on the river, nature, and love.',86),
('Chhau Nritya(Odisha)','Accompanies vigorous martial dance forms depicting epics like Ramayana or Mahabharata. Masked dance performances in western Odisha (Mayurbhanj, Seraikela, Jharkhand border).',86),
('Sambalpuri(Odisha)','Often accompanied by dhol, madal, mahuri; used in weddings, festivals, and harvest celebrations. Western Odisha, performed in traditional dress.',86),
('Ghoda Nacha(Odisha)','Part of the Ghoda Nacha dance tradition where performers mimic horse movements.',86),
('Pala(Odisha)','Storytelling in verse, often about mythological tales or social messages; performed with singing, dancing, and musical instruments.',86),
('Kathi Nacha(Odisha)','Songs accompany stick dances, often during festivals and community celebrations.',86),
('Suanga(Odisha)','Combines storytelling, singing, and acting; often depicts village legends or social themes.',86),
('Bhopa(Odisha)','Performed by traveling minstrels, accompanied by simple percussion instruments.',86),
('Prahallada Nataka(Odisha)','Story of Prahlada, a devotee of Vishnu, and the evil king Hiranyakashipu.  Performed during festivals, often with music, singing, and acting. Includes dialogues, songs, and instrumental accompaniment (mardhala, mukhabina, manjira & harmonium).',86),
('Bharata Leela(Odisha)','Life and love story of Arjun and Subhadra or stories from the Mahabharata. Performs with chhanda, odissi, champu and semi classical music',86),
('Radha Prema Leela(Odisha)','Romantic and divine exploits of Radha and Krishna. Includes songs, dances, and enactments of Krishna’s leelas.',86),
('Rama Leela(Odisha)','Episodes from Ramayana, especially Rama’s battle with Ravana. Enacted with dialogues, singing, and combat sequences.',86),
('Krushna Leela(Odisha)','Life and exploits of Lord Krishna from childhood to adulthood.',86);
